name: glass_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - seaborn
      - scipy
      - notebook
      - jupyterlab
      - pillow
      - opencv-python
      - scikit-learn